### ISSUE TITLE
Peak activity tolerance (feature)

### ISSUE THREAD

**Issue by gugau-fr** [languitar/autosuspend#18]
Hello,

This is a small feature request if you allow me. It would be great the CPU load check (others too ?) to have a tolerance to peak activity. I mean, sometimes a process can use the CPU intensively but only for some seconds or less, this is identified as an activity but often it is not. Also, using a higher threshold make low CPU activity of some processes being ignored even when it runs for a longer period (several seconds or minutes). Note that this scenario has more meaning in case the checks are run frequently (every one or two seconds).

Actually I use a home made script that ignore activities if the amount is less than a configured percentage. In your code, that mean testing in the load check:
`ignored_activities/checks_counter >= activity_tolerance`
Considering :

- the check don't return true if the ignored activity percentage is below the tolerance
- ignored_activities is the count of activity detected since the last time the check returned true
- checks_counter is the count of calls to the check since the last time the check returned true
- activity_tolerance is a configuration value

Finally, to avoid going to suspend when idle_time is expired while a process was started some seconds ago (with CPU activity), I test if there is no strict activity (I mean, including ignored activities) during a shorter period (shorter than idle_time).
With this, we have a more fine control of whether or not the computer should be suspended.

Thanks !

**Comment by languitar** [comment]
Actually, I don't have a check direct CPU usage because of such problems. Instead, load average is, as the name says, an average that ignores small spikes. Load should be more reliable in that direction but is less easy to grasp. In any case, I wouldn't like to see autosuspend run the checks every few seconds because that would cause some significant overhead by autosuspend itself.

My general feeling is that using network bandwidth or cpu utilization / load, in general, is most of the actual issue. My tendency is to say that there should be more dedicated checks that provide a clear decision based on real features of task and processes running on the host. For instance, I am much happier about checking whether certain ports are connected (boolean decision, no guessing or thresholds) than using a network bandwidth check where the threshold is never clear. So my general goal for autosuspend is to add more of these specific checks that are more reliable and predictable than to hack around with more and more complex algorithms to determine activity from system metrics such as cpu usage etc.

**Comment by gugau-fr** [comment]
Thanks for your quick answer. I understand you want to keep the checks reliable and simple, it's true your tool should be used that way. I'm not sure the load average is enough for my use cases (my algorithm is more complex as you said) but I should try to create a full configuration to check all the apps running on my server instead (lot of stuff), once feature #9 is implemented :) (another thing my ugly script do). I stay tuned !

**Comment by languitar** [comment]
Could you please line out what you are running on your sever that determines activity? I will see what is missing then.

**Comment by gugau-fr** [comment]
I thinks nothing is missing in the actual checks available. Some of my stuff : transmission-daemon, sonarr, Mumur, apache webdav, Syncthing, MPD daemon, XBMC, some cron tasks, ... So either I  create a configuration with one rule for each software (using port usage, process lookup for non-daemon processes, ...) either I have a rule for all (with CPU usage, brandwidth usage). To be more precise, I use the computer as HTPC/NAS & co. So sometimes there is a low CPU usage but I need to keep it up (MDP, Murmur or when I'm using the desktop) and sometimes there is a high CPU usage for a short period but I want it to be ignored (some sonarr task for instance) but not if it's a process than has just started. That why I needed a more complex algorithm.

**Comment by languitar** [comment]
I think there is a misunderstanding. You have a single configuration for autosuspend and the daemon is intended to run only once. That configuration has to detect all valid activity that should prevent the server from sleeping.

For MPD, for instance, there is no need to use the CPU usage or load at all. There is a dedicated check that detects whether MPD is playing something or not. For most other services, you can probably use the port check to detect whether a remote client is connected or not.

Maybe you just try to use autosuspend and once you know exactly what is missing / why the sever goes to sleep despite being used, you can open a more focused feature request.
